---
# tasks file for restore_6_Nginx
- name: Stop and stop dependent containers
  community.docker.docker_compose_v2:
    project_src: "{{ OTUS_PROF_PROJECT_PATH }}"
    files: "{{ item.files }}"
    state: "{{ item.state }}"
  loop: "{{ dependent_containers }}"

- name: Remove directories
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ archives }}"

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "{{ OTUS_PROF_PROJECT_PATH }}/backups/folder/{{ item.file_gz }}"
    dest: "{{ OTUS_PROF_PROJECT_PATH }}"
    remote_src: yes
  loop: "{{ archives }}"