services:

  wordpress_1:
    container_name: wordpress_1
    image: wordpress:6.7.2-php8.2-apache
    restart: always
    networks:
      otus-pro-net:
        ipv4_address: ${IP_WORDPRESS_1}
    # ports:
    #   - 8081:80
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_NAME_MYSQL_DB1}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ${OTUS_PROF_PROJECT_PATH}/wordpress:/var/www/html
    env_file:
      - .env

  wordpress_2:
    container_name: wordpress_2
    image: wordpress:6.7.2-php8.2-apache
    restart: always
    networks:
      otus-pro-net:
        ipv4_address: ${IP_WORDPRESS_2}
    # ports:
    #   - 8082:80
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_NAME_MYSQL_DB1}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ${OTUS_PROF_PROJECT_PATH}/wordpress:/var/www/html
    env_file:
      - .env

networks:
  otus-pro-net:
    external: true
    name: otus-pro-net
