---
# tasks file for network_setup
- name: Create Docker network otus-pro-net
  community.docker.docker_network:
    name: otus-pro-net
    ipam_config:
      - subnet: "172.20.0.0/16"
        iprange: "172.20.240.0/24"
    state: present

- name: Allow loopback interface
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow established and related connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow HTTP (port 80) from any source
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

- name: Allow HTTPS (port 443) from any source
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT

- name: Allow SSH (port 22) only from 78.138.157.10
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: 78.138.157.10
    destination_port: 22
    jump: ACCEPT

- name: Drop all other incoming traffic
  ansible.builtin.iptables:
    chain: INPUT
    jump: DROP